---
title: "My Data Visualization Collection"
author: "by Orhan Aktas"
date: '2022-08-17'
output:   
    html_document:
      df_print: !expr knitr::kable
      toc: yes
      number_sections: yes
      toc_depth: 2
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  class.source = "bg-warning text-warning"
)
```

#### Required Libraries {.unlisted .unnumbered}

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(ggthemes)
library(ggtext)
library(fmsb)
library(patchwork)
```

# Introduction

## radar charts
```{r}
 data <- read_excel("data/datasets.xlsx", sheet = "radar")
```

```{r}
scenarios <- data %>% 
  t %>% 
  as_tibble %>% 
  set_names(data %>% select(Dimensions)%>% unlist) %>% 
  slice(-1)%>% 
  mutate_all(as.integer)

scenarios <- rbind(rep(100, 12), rep(0, 12), scenarios)

scenarios <- data %>% 
  names() %>% 
  as_tibble %>% 
  slice(-1)%>% 
  add_row(value = "max scale", .before = 1)%>% 
  add_row(value = "min scale", .before = 1) %>% 
  cbind(scenarios) %>% 
  column_to_rownames(var = "value")
```



```{r }
  # Simple Pie Chart

  par(oma = c(0, 0, 0, 0))
  par(mar = c(2, 2, 2, 2))
  pie_slices <- c(6, 4, 2)
  pie_col <- c("#FFF0F5", "#F0FFF0", "#FAFAD2")
  lbls <- c("Economic\nProsperity", "Mobility\nTrends", "Social\nAspects")
  # pie(slices, labels = lbls, main="Pie Chart of Countries")
  pie(pie_slices, col = pie_col, init.angle = 285, labels = lbls, border = "navy", lty = 2)
  
  par(new = TRUE)
    par(oma = c(2, 2, 2, 2))
  par(mar = c(4, 4, 4, 4))
  radarchart(scenarios[1:3, ],
    axistype = 1,
    axislabcol = "grey",
    caxislabels = c("0", "25", "50", "75", "100"),
    calcex = 0.75,
    seg = 4,
    cglcol = "grey",
    cglty = 1,
    vlcex = 0.4,
    palcex = 1,
    pcol = 2,
    pty = 32,
    plty = 1,
    plwd = 6,
    title = row.names(scenarios[3, ])
  )
  
dev.off()

```
ggradar will be experimented. 
figpatch can patch external image such as png.

